import * as nodeFs from "node:fs";
import { teamDescriptions } from "./api.js";
import type {
  CodeOwnersConfig,
  FsLike,
  GenerateOptions,
  MatchRule,
  ResolvedRule,
  Team,
} from "./types.js";
import {
  evaluateRules,
  flattenOwnership,
  matchesCodeownersPattern,
  resolveOwnerStages,
  unique,
  walkFiles,
  type FlatEntry,
} from "./resolve.js";

/**
 * Generate CODEOWNERS file content from a config.
 *
 * The generator works from ground truth. It reads the real files in the
 * repository, computes the exact owner set for each file, then compresses
 * those per-file owners into the smallest set of CODEOWNERS lines that
 * reproduces them. It checks the result before it returns.
 *
 * Direct `own()` declarations are always emitted. The filesystem does not
 * affect them, because an empty directory still has an owner.
 */
export function generate(
  config: CodeOwnersConfig,
  options?: GenerateOptions,
): string {
  const always = config.always ?? [];
  const rootDir = options?.rootDir ?? process.cwd();
  const fs = options?.fs ?? (nodeFs as unknown as FsLike);

  // 1. Flatten ownership rules, normalizing paths
  const flatEntries = flattenOwnership(config.own);

  // 2. Direct ownership rules, sorted by specificity (ascending)
  const directRules: ResolvedRule[] = flatEntries.map((entry) => ({
    path: entry.path,
    owners: unique([...entry.owners, ...always]),
  }));
  directRules.sort((a, b) => specificity(a.path) - specificity(b.path));

  // 3. Ground truth: the exact owner set of every real file
  const files = walkFiles(rootDir, fs);
  const stages = resolveOwnerStages(config, files);
  const ownersByFile = stages[stages.length - 1];

  // 4. Compress the per-file owners back into patterns
  const matchGroups = compressMatchRules(
    config.match ?? [],
    files,
    stages,
    directRules,
    flatEntries,
    always,
  );

  // 5. Check the emitted rules against ground truth
  verifyOutput(
    [...directRules, ...matchGroups.flatMap((g) => g.rules)],
    ownersByFile,
  );

  // 6. Format with sections and grouping
  const lines: string[] = [
    "# This file is auto-generated by codeowners-util. Do not edit directly.",
  ];

  // Direct ownership, grouped by team
  if (directRules.length > 0) {
    lines.push("", "# ── Direct ownership ──────────────────────────────");
    const grouped = groupByOwners(directRules, flatEntries);
    for (const group of grouped) {
      lines.push("");
      // Add own() descriptions as comments above the group
      for (const desc of group.descriptions) {
        lines.push(`# ${desc}`);
      }
      // Build label with team descriptions where available
      // config.teams takes precedence, falls back to team() descriptions
      const labelParts = group.label === "(no owners)"
        ? ["(no owners)"]
        : group.rules[0].owners.map((owner) => {
            const desc = config.teams?.[owner] ?? teamDescriptions.get(owner);
            return desc ? `${owner} (${desc})` : owner;
          });
      lines.push(`# ${labelParts.join(", ")}`);
      for (const rule of group.rules) {
        lines.push(formatRule(rule));
      }
    }
  }

  // Match rules, grouped by source pattern, in declaration order
  for (const group of matchGroups) {
    lines.push("", `# ── Match: ${group.pattern} ──`);
    if (group.description) {
      lines.push(`# ${group.description}`);
    }
    lines.push("");
    for (const rule of group.rules) {
      lines.push(formatRule(rule));
    }
  }

  return lines.join("\n") + "\n";
}

// ── Internals ──────────────────────────────────────────

interface PatternGroup {
  pattern: string;
  description?: string;
  rules: ResolvedRule[];
}

/**
 * Turn per-file owners into CODEOWNERS lines, one group per match rule.
 *
 * For each rule:
 * 1. Collect the files that the rule matches.
 * 2. If every matched file has the same owners, emit the pattern once.
 * 3. Otherwise group the files by scope and emit one line per scope.
 * 4. If one scope holds files with different owners, emit one line per file.
 *
 * A final pass drops every line that does not change the result.
 */
function compressMatchRules(
  matchRules: readonly MatchRule[],
  files: readonly string[],
  stages: readonly Map<string, Team[]>[],
  directRules: readonly ResolvedRule[],
  flatEntries: readonly FlatEntry[],
  always: readonly Team[],
): PatternGroup[] {
  const groups: PatternGroup[] = [];

  const ownersByFile = stages[stages.length - 1];

  for (const [ruleIndex, rule] of matchRules.entries()) {
    const matched = files.filter((f) =>
      matchesCodeownersPattern(rule.pattern, f),
    );
    if (matched.length === 0) continue;

    // The state after this rule, so a later rule's change is not blamed here.
    const afterThisRule = stages[ruleIndex + 1];
    const ownersOf = (f: string) => afterThisRule.get(f) ?? [];
    const lines: ResolvedRule[] = [];

    // A broad line first, so later scoped lines can override it.
    //
    // An `only` rule sets its owners outright, so one global line states the
    // whole rule. An `add` rule stacks on inherited owners, so a global line
    // is correct only for files that inherit from the catch-all. Without a
    // catch-all there is no safe global line, and every line names a scope.
    const catchAll = flatEntries.find((e) => e.path === "*");
    if ("only" in rule) {
      lines.push({
        path: rule.pattern,
        owners: unique([...rule.only, ...always]),
      });
    } else if (catchAll) {
      // Pick a file that still holds exactly the catch-all owners when this
      // rule starts. Comparing against own() alone is not enough: an earlier
      // rule may already have changed the file, and then the global line
      // would carry that earlier rule's teams to unrelated files.
      const catchAllOwners = unique([...catchAll.owners, ...always]);
      const beforeThisRule = stages[ruleIndex];
      const inherited = matched.find((f) =>
        sameOwners(beforeThisRule.get(f) ?? [], catchAllOwners),
      );
      if (inherited) {
        lines.push({ path: rule.pattern, owners: ownersOf(inherited) });
      }
    }

    // Then one line per scope, for the scopes that differ.
    const byScope = new Map<string, string[]>();
    for (const f of matched) {
      const scope = scopeFor(rule.pattern, f);
      const list = byScope.get(scope);
      if (list) list.push(f);
      else byScope.set(scope, [f]);
    }

    for (const [scope, scopeFiles] of byScope) {
      const keys = new Set(scopeFiles.map((f) => ownerKey(ownersOf(f))));
      if (keys.size === 1) {
        lines.push({
          path: scopedPath(rule.pattern, scope),
          owners: ownersOf(scopeFiles[0]),
        });
      } else {
        // Last resort: one line per file. Always correct, never ambiguous.
        for (const f of scopeFiles) {
          lines.push({ path: f, owners: ownersOf(f) });
        }
      }
    }
    lines.sort((a, b) => specificity(a.path) - specificity(b.path));
    groups.push({
      pattern: rule.pattern,
      description: rule.description,
      rules: lines,
    });
  }

  return dropRedundantLines(groups, directRules, ownersByFile, files);
}

/**
 * Remove every emitted line that does not change the outcome.
 *
 * This replaces the old subsumption heuristic. Instead of comparing pattern
 * strings, it removes a line and checks whether any file changes owner.
 */
function dropRedundantLines(
  groups: PatternGroup[],
  directRules: readonly ResolvedRule[],
  ownersByFile: Map<string, Team[]>,
  files: readonly string[],
): PatternGroup[] {
  interface Line {
    groupIndex: number;
    rule: ResolvedRule;
    dropped: boolean;
  }

  const lines: Line[] = groups.flatMap((g, groupIndex) =>
    g.rules.map((rule) => ({ groupIndex, rule, dropped: false })),
  );

  const holds = (): boolean => {
    const active = [
      ...directRules,
      ...lines.filter((l) => !l.dropped).map((l) => l.rule),
    ];
    return files.every((f) =>
      sameOwners(evaluateRules(active, f), ownersByFile.get(f) ?? []),
    );
  };

  // Try the narrowest lines first. A narrow line that repeats what a broad
  // line already says is the redundant one, so the broad line survives and
  // keeps covering files that are added later.
  for (const line of [...lines].reverse()) {
    line.dropped = true;
    if (!holds()) line.dropped = false;
  }

  return groups
    .map((g, i) => ({
      ...g,
      rules: lines
        .filter((l) => l.groupIndex === i && !l.dropped)
        .map((l) => l.rule),
    }))
    .filter((g) => g.rules.length > 0);
}

/**
 * Fail loudly when the emitted rules disagree with ground truth.
 *
 * A failure here means the compression step has a defect. It never means the
 * config is wrong, so the message asks for a bug report.
 */
function verifyOutput(
  rules: readonly ResolvedRule[],
  ownersByFile: Map<string, Team[]>,
): void {
  for (const [file, want] of ownersByFile) {
    const got = evaluateRules(rules, file);
    if (sameOwners(got, want)) continue;
    throw new Error(
      [
        "codeowners-util: the generated rules do not match the resolved owners.",
        `  file:     ${file}`,
        `  expected: ${want.join(" ") || "(no owners)"}`,
        `  emitted:  ${got.join(" ") || "(no owners)"}`,
        "This is a defect in codeowners-util. Please report it.",
      ].join("\n"),
    );
  }
}

/** The leading segments of a pattern that hold no glob characters. */
function literalPrefix(tail: string): string {
  const literal: string[] = [];
  for (const segment of tail.split("/")) {
    if (segment.includes("*") || segment.includes("?")) break;
    literal.push(segment);
  }
  return literal.join("/");
}

/**
 * The path in front of a pattern's literal anchor, for one file.
 *
 * Pattern `**\/locales\/**\/*.json` and file `libs/a/locales/en/x.json` give
 * `libs/a`. A root-anchored pattern has no scope.
 */
function scopeFor(pattern: string, file: string): string {
  if (!pattern.startsWith("**/")) return "";

  const fileSegments = file.split("/");
  const parentDir = () => fileSegments.slice(0, -1).join("/");

  const literal = literalPrefix(pattern.slice(3));
  if (!literal) return parentDir();

  const literalSegments = literal.split("/");
  for (let i = 0; i + literalSegments.length <= fileSegments.length; i++) {
    const hit = literalSegments.every((s, j) => fileSegments[i + j] === s);
    if (hit) return fileSegments.slice(0, i).join("/");
  }
  return parentDir();
}

/** Re-anchor a pattern under a scope. */
function scopedPath(pattern: string, scope: string): string {
  if (!pattern.startsWith("**/")) return pattern;
  const tail = pattern.slice(3);
  return scope ? `${scope}/${tail}` : tail;
}

/** A stable key for an owner set, ignoring order. */
function ownerKey(owners: readonly Team[]): string {
  return [...owners].sort().join(" ");
}

/** Count non-glob segments as a proxy for specificity */
function specificity(pattern: string): number {
  return pattern.split("/").filter((s) => s !== "**").length;
}

function sameOwners(a: readonly Team[], b: readonly Team[]): boolean {
  if (a.length !== b.length) return false;
  const setA = new Set(a);
  for (const owner of b) {
    if (!setA.has(owner)) return false;
  }
  return true;
}

function formatRule(rule: ResolvedRule): string {
  if (rule.owners.length === 0) {
    return rule.path;
  }
  return `${rule.path} ${rule.owners.join(" ")}`;
}

// ── Formatting helpers ─────────────────────────────────

interface OwnerGroup {
  label: string;
  descriptions: string[];
  rules: ResolvedRule[];
}

/**
 * Group resolved rules by their owner set for visual clustering.
 * Each group gets a label showing the team name(s) and collects descriptions.
 */
function groupByOwners(
  rules: ResolvedRule[],
  flatEntries: FlatEntry[],
): OwnerGroup[] {
  const groups: OwnerGroup[] = [];
  const seen = new Map<string, OwnerGroup>();

  // Build lookup from path → descriptions
  const pathDescriptions = new Map<string, string[]>();
  for (const entry of flatEntries) {
    if (entry.descriptions.length > 0) {
      pathDescriptions.set(entry.path, entry.descriptions);
    }
  }

  for (const rule of rules) {
    const key = rule.owners.join(" ");
    const existing = seen.get(key);
    if (existing) {
      existing.rules.push(rule);
      // Collect descriptions from this path
      const descs = pathDescriptions.get(rule.path);
      if (descs) {
        for (const d of descs) {
          if (!existing.descriptions.includes(d)) {
            existing.descriptions.push(d);
          }
        }
      }
    } else {
      const descs = pathDescriptions.get(rule.path) ?? [];
      const group: OwnerGroup = {
        label: rule.owners.length > 0 ? rule.owners.join(", ") : "(no owners)",
        descriptions: [...descs],
        rules: [rule],
      };
      seen.set(key, group);
      groups.push(group);
    }
  }

  return groups;
}
