import * as nodeFs from "node:fs";
import { join, relative } from "node:path";
import type {
  CodeOwnersConfig,
  FsLike,
  GenerateOptions,
  MatchRule,
  OwnershipRule,
  ResolvedRule,
  Team,
} from "./types.js";

/**
 * Generate CODEOWNERS file content from a config.
 *
 * Match rules are resolved against the actual filesystem — only emitting
 * rules for directories that contain matching files, and discovering
 * directories not declared in `own()`.
 */
export function generate(
  config: CodeOwnersConfig,
  options?: GenerateOptions,
): string {
  const always = config.always ?? [];
  const rootDir = options?.rootDir ?? process.cwd();
  const fs = options?.fs ?? (nodeFs as unknown as FsLike);

  // 1. Flatten ownership rules, normalizing paths
  const flatEntries = flattenOwnership(config.own);

  // 2. Resolve direct ownership rules, sorted by specificity (ascending)
  const directRules: ResolvedRule[] = flatEntries.map((entry) => ({
    path: entry.path,
    owners: unique([...entry.owners, ...always]),
  }));
  directRules.sort((a, b) => specificity(a.path) - specificity(b.path));

  // 3. Expand match rules against the filesystem
  const matchedRules = expandMatchRules(
    config.match ?? [],
    flatEntries,
    always,
    rootDir,
    fs,
  );

  // 4. Deduplicate: more specific pattern wins, equal specificity last wins
  const deduped = deduplicateBySpecificity(matchedRules);

  // 5. Remove rules subsumed by a broader pattern with identical owners
  //    e.g. **/locales/**/*.json already covers libs/air/locales/**/*.json
  //    when both have the same owners (typical with `only` rules + catch-all)
  const pruned = removeSubsumedRules(deduped);

  // 6. Sort match rules by specificity (ascending)
  pruned.sort((a, b) => specificity(a.path) - specificity(b.path));

  // 6. Format with sections and grouping
  const lines: string[] = [
    "# This file is auto-generated by codeowners-util. Do not edit directly.",
  ];

  // Direct ownership, grouped by team
  if (directRules.length > 0) {
    lines.push("", "# ── Direct ownership ──────────────────────────────");
    const grouped = groupByOwners(directRules);
    for (const group of grouped) {
      lines.push("", `# ${group.label}`);
      for (const rule of group.rules) {
        lines.push(formatRule(rule));
      }
    }
  }

  // Match rules, grouped by source pattern
  if (pruned.length > 0) {
    const matchGroups = groupByPattern(pruned, matchedRules);
    for (const group of matchGroups) {
      lines.push("", `# ── Match: ${group.pattern} ──`);
      lines.push("");
      for (const rule of group.rules) {
        lines.push(formatRule(rule));
      }
    }
  }

  return lines.join("\n") + "\n";
}

// ── Internals ──────────────────────────────────────────

interface FlatEntry {
  path: string;
  owners: Team[];
}

/** Normalize a path: strip trailing slashes */
function normalizePath(p: string): string {
  if (p === "/" || p === "*") return p;
  return p.replace(/\/+$/, "");
}

/**
 * Flatten ownership rules into one entry per unique path.
 * Normalizes paths and merges co-ownership automatically.
 */
function flattenOwnership(rules: readonly OwnershipRule[]): FlatEntry[] {
  const byPath = new Map<string, FlatEntry>();
  const order: string[] = [];

  for (const rule of rules) {
    for (const rawPath of rule.paths) {
      const path = normalizePath(rawPath);
      const existing = byPath.get(path);
      if (existing) {
        for (const owner of rule.owners) {
          if (!existing.owners.includes(owner)) {
            existing.owners.push(owner);
          }
        }
      } else {
        const entry = { path, owners: [...rule.owners] };
        byPath.set(path, entry);
        order.push(path);
      }
    }
  }

  return order.map((path) => byPath.get(path)!);
}

interface ExpandedMatch {
  resolvedPath: string;
  owners: Team[];
  sourcePattern: string;
}

/**
 * Expand match rules against the filesystem.
 *
 * For each match rule:
 * 1. Catch-all `*` always produces a global pattern
 * 2. For each owned path, check the filesystem: is it a directory whose
 *    resolved pattern prefix exists? If so, emit the rule.
 * 3. Discover directories on disk that match but aren't declared in own().
 */
function expandMatchRules(
  matchRules: readonly MatchRule[],
  flatEntries: FlatEntry[],
  always: readonly Team[],
  rootDir: string,
  fs: FsLike,
): ExpandedMatch[] {
  const results: ExpandedMatch[] = [];

  for (const rule of matchRules) {
    const ownedDirPaths = new Set<string>();

    for (const entry of flatEntries) {
      if (entry.path === "*") {
        // Catch-all always produces global pattern
        const resolved = resolvePattern(entry.path, rule.pattern);
        const owners: Team[] =
          "only" in rule
            ? unique([...rule.only, ...always])
            : unique([...entry.owners, ...rule.add, ...always]);
        results.push({
          resolvedPath: resolved,
          owners,
          sourcePattern: rule.pattern,
        });
        continue;
      }

      // Is this a directory on disk?
      if (!isDirectory(join(rootDir, entry.path), fs)) continue;

      ownedDirPaths.add(entry.path);

      // Does the resolved pattern's directory prefix exist?
      const resolved = resolvePattern(entry.path, rule.pattern);
      if (!hasMatchingPath(resolved, rootDir, fs)) continue;

      const owners: Team[] =
        "only" in rule
          ? unique([...rule.only, ...always])
          : unique([...entry.owners, ...rule.add, ...always]);

      results.push({
        resolvedPath: resolved,
        owners,
        sourcePattern: rule.pattern,
      });
    }

    // Discover directories with matching files not in own()
    const discoveredDirs = findMatchingDirectories(
      rule.pattern,
      rootDir,
      fs,
    );
    for (const dir of discoveredDirs) {
      if (ownedDirPaths.has(dir)) continue;

      const parentOwners = findOwners(dir, flatEntries);
      const resolved = resolvePattern(dir, rule.pattern);
      const owners: Team[] =
        "only" in rule
          ? unique([...rule.only, ...always])
          : unique([...parentOwners, ...rule.add, ...always]);

      results.push({
        resolvedPath: resolved,
        owners,
        sourcePattern: rule.pattern,
      });
    }
  }

  return results;
}

/** Check if a path is a directory on disk */
function isDirectory(absPath: string, fs: FsLike): boolean {
  try {
    return fs.statSync(absPath).isDirectory();
  } catch {
    return false;
  }
}

/**
 * Check if a resolved pattern could match files on disk by verifying
 * that its non-glob directory prefix exists.
 *
 * "libs/search/locales/en/sample.json" → check "libs/search/locales/en"
 * "libs/search/.env*" → check "libs/search"
 */
function hasMatchingPath(
  resolvedPattern: string,
  rootDir: string,
  fs: FsLike,
): boolean {
  const segments = resolvedPattern.split("/");
  const dirSegments: string[] = [];
  for (const seg of segments) {
    if (seg.includes("*") || seg.includes("?")) break;
    dirSegments.push(seg);
  }
  // Remove the last segment if it's a filename (the directory is its parent)
  if (dirSegments.length > 0) {
    const last = dirSegments[dirSegments.length - 1];
    if (last.includes(".")) {
      dirSegments.pop();
    }
  }
  const dirPath = dirSegments.join("/");
  if (!dirPath) return true; // pattern starts with glob — always matches
  return isDirectory(join(rootDir, dirPath), fs);
}

/**
 * Load ignore patterns from .gitignore + built-in defaults.
 * Returns a set of directory names/patterns to skip during traversal.
 */
function loadIgnorePatterns(rootDir: string, fs: FsLike): Set<string> {
  // Always ignore these
  const patterns = new Set(["node_modules", ".git"]);

  try {
    const content = fs.readFileSync(join(rootDir, ".gitignore"), "utf-8");
    for (const raw of content.split("\n")) {
      const line = raw.trim();
      if (!line || line.startsWith("#") || line.startsWith("!")) continue;
      // Strip trailing slash and leading slash
      const cleaned = line.replace(/^\//, "").replace(/\/+$/, "");
      if (cleaned) patterns.add(cleaned);
    }
  } catch {
    // No .gitignore or can't read it
  }

  return patterns;
}

/**
 * Check if a relative path should be ignored based on gitignore patterns.
 * A path is ignored if any of its segments match an ignore pattern.
 */
function isIgnored(relPath: string, patterns: Set<string>): boolean {
  const segments = relPath.split("/");
  for (const seg of segments) {
    if (seg.startsWith(".") || patterns.has(seg)) return true;
  }
  return false;
}

/**
 * Find all directories (relative to rootDir) that contain files matching
 * the given pattern. Extracts the directory anchor from the pattern and
 * walks the filesystem for it — skipping ignored directories BEFORE
 * descending into them to avoid scanning node_modules, .git, etc.
 */
function findMatchingDirectories(
  pattern: string,
  rootDir: string,
  fs: FsLike,
): Set<string> {
  const dirs = new Set<string>();
  const ignorePatterns = loadIgnorePatterns(rootDir, fs);

  // Extract the searchable directory anchor from the pattern.
  const stripped = pattern.startsWith("**/") ? pattern.slice(3) : pattern;
  const segments = stripped.split("/");
  const anchorSegments: string[] = [];
  for (const seg of segments) {
    if (seg.includes("*") || seg.includes("?")) break;
    anchorSegments.push(seg);
  }
  const anchor = anchorSegments.join("/");

  if (!anchor) {
    // No directory anchor (e.g. "**/.env*"). Discovery isn't meaningful —
    // owned directories are already checked individually via hasMatchingPath,
    // and catch-all * handles the global pattern.
    return dirs;
  }

  // Manual recursive walk — skip ignored dirs BEFORE descending
  function walk(absDir: string, relDir: string): void {
    let entries: readonly { name: string; isDirectory(): boolean }[];
    try {
      entries = fs.readdirSync(absDir, { withFileTypes: true });
    } catch {
      return;
    }

    for (const entry of entries) {
      if (!entry.isDirectory()) continue;

      const name = entry.name;

      // Skip before descending — this is the key optimization
      if (name.startsWith(".") || ignorePatterns.has(name)) continue;

      const rel = relDir ? `${relDir}/${name}` : name;

      // Check if this directory matches the anchor
      if (rel.endsWith(anchor) || rel.includes(`/${anchor}`)) {
        const anchorIdx = rel.indexOf(anchor);
        const parent = rel.slice(0, anchorIdx).replace(/\/$/, "");
        if (parent) {
          dirs.add(parent);
        }
      }

      // Recurse
      walk(join(absDir, name), rel);
    }
  }

  walk(rootDir, "");
  return dirs;
}

/**
 * Find the owners for a path by matching against the most specific owned
 * prefix. Falls back to catch-all `*` if nothing else matches.
 */
function findOwners(path: string, flatEntries: FlatEntry[]): Team[] {
  let bestMatch: FlatEntry | undefined;
  let bestLen = -1;

  for (const entry of flatEntries) {
    if (entry.path === "*") {
      if (bestLen < 0) {
        bestMatch = entry;
        bestLen = 0;
      }
      continue;
    }
    if (
      path === entry.path ||
      path.startsWith(entry.path + "/")
    ) {
      if (entry.path.length > bestLen) {
        bestMatch = entry;
        bestLen = entry.path.length;
      }
    }
  }

  return bestMatch ? [...bestMatch.owners] : [];
}

/**
 * When multiple match rules produce the same resolved path,
 * the more specific source pattern wins. Equal specificity: last wins.
 */
function deduplicateBySpecificity(matches: ExpandedMatch[]): ResolvedRule[] {
  const byPath = new Map<string, ExpandedMatch>();

  for (const m of matches) {
    const existing = byPath.get(m.resolvedPath);
    if (
      !existing ||
      specificity(m.sourcePattern) >= specificity(existing.sourcePattern)
    ) {
      byPath.set(m.resolvedPath, m);
    }
  }

  return Array.from(byPath.values()).map((m) => ({
    path: m.resolvedPath,
    owners: m.owners,
  }));
}

/**
 * Resolve a match pattern relative to an owned path.
 * A leading double-star-slash prefix is stripped and scoped under the
 * owned path. Catch-all `*` keeps the pattern global.
 */
function resolvePattern(ownedPath: string, pattern: string): string {
  if (ownedPath === "*") {
    return pattern;
  }
  if (pattern.startsWith("**/")) {
    return `${ownedPath}/${pattern.slice(3)}`;
  }
  return `${ownedPath}/${pattern}`;
}

/** Count non-glob segments as a proxy for specificity */
function specificity(pattern: string): number {
  return pattern.split("/").filter((s) => s !== "**").length;
}

function unique(arr: readonly Team[]): Team[] {
  return [...new Set(arr)];
}

/**
 * Remove rules that are subsumed by a broader pattern with identical owners.
 * A global pattern like ** /locales/*.json covers libs/air/locales/*.json —
 * if they have the same owners, the specific rule is redundant.
 */
function removeSubsumedRules(rules: ResolvedRule[]): ResolvedRule[] {
  // Collect all global patterns (starting with **/)
  const globals = rules.filter((r) => r.path.startsWith("**/"));

  if (globals.length === 0) return rules;

  return rules.filter((rule) => {
    // Don't filter out the global patterns themselves
    if (rule.path.startsWith("**/")) return true;

    // Check if any global pattern subsumes this rule with identical owners
    for (const g of globals) {
      const suffix = g.path.slice(3); // strip "**/""
      if (
        rule.path.endsWith(suffix) &&
        sameOwners(g.owners, rule.owners)
      ) {
        return false; // subsumed — drop it
      }
    }

    return true;
  });
}

function sameOwners(a: readonly Team[], b: readonly Team[]): boolean {
  if (a.length !== b.length) return false;
  const setA = new Set(a);
  for (const owner of b) {
    if (!setA.has(owner)) return false;
  }
  return true;
}

function formatRule(rule: ResolvedRule): string {
  if (rule.owners.length === 0) {
    return rule.path;
  }
  return `${rule.path} ${rule.owners.join(" ")}`;
}

// ── Formatting helpers ─────────────────────────────────

interface OwnerGroup {
  label: string;
  rules: ResolvedRule[];
}

/**
 * Group resolved rules by their owner set for visual clustering.
 * Each group gets a label showing the team name(s).
 */
function groupByOwners(rules: ResolvedRule[]): OwnerGroup[] {
  const groups: OwnerGroup[] = [];
  const seen = new Map<string, OwnerGroup>();

  for (const rule of rules) {
    const key = rule.owners.join(" ");
    const existing = seen.get(key);
    if (existing) {
      existing.rules.push(rule);
    } else {
      const group: OwnerGroup = {
        label: rule.owners.length > 0 ? rule.owners.join(", ") : "(no owners)",
        rules: [rule],
      };
      seen.set(key, group);
      groups.push(group);
    }
  }

  return groups;
}

interface PatternGroup {
  pattern: string;
  rules: ResolvedRule[];
}

/**
 * Group match-expanded rules by their source pattern.
 * Preserves the specificity sort within each group.
 */
function groupByPattern(
  deduped: ResolvedRule[],
  expanded: ExpandedMatch[],
): PatternGroup[] {
  // Build a map from resolved path → source pattern
  const pathToPattern = new Map<string, string>();
  for (const m of expanded) {
    pathToPattern.set(m.resolvedPath, m.sourcePattern);
  }

  const groups: PatternGroup[] = [];
  const seen = new Map<string, PatternGroup>();

  for (const rule of deduped) {
    const pattern = pathToPattern.get(rule.path) ?? "unknown";
    const existing = seen.get(pattern);
    if (existing) {
      existing.rules.push(rule);
    } else {
      const group: PatternGroup = { pattern, rules: [rule] };
      seen.set(pattern, group);
      groups.push(group);
    }
  }

  return groups;
}
